### ISSUE TITLE
docker in out

### ISSUE THREAD

**Issue by aremazeilles** [eurobench/pi_python_duration#5]
According to this [discussion](https://github.com/madrob-beast/madrob_beast_pi/issues/2#issuecomment-614855254), it seems that the creation of the in out folder is not necessary, and that they can be created on the fly.

This would need to be verified, and, if true, the [related lines](https://github.com/eurobench/pi_python_duration/blob/master/Dockerfile#L35) should be removed. 

Similar change should be deployed on the other examples.

**Comment by alfonsotecnalia** [comment]
The problem I see here is that if you define a user inside the docker image (pi_runner), it will not have access to write things in this automatically created folder (only the root could to do it). Is it a good practice (a must) to add a different user to root? If yes, then:
- keep our approach
- find a way so the user has access to these automatically generated folders
If not, remove the lines corresponding to the creation of the user pi_runner, the copy of the src to its folder, etc.

**Comment by alfonsotecnalia** [comment]
Seems to work, need to make more detailed test.

**Comment by alfonsotecnalia** [comment]
I have checked it with the pi_csic docker image and it works making little changes to the pi_manager. I will create a branch for the pi_manager and the existing pis and merge them when the trials finish.

**Comment by alfonsotecnalia** [comment]
It works only for normal dockers. In pi_manager we are making 'docker inside docker' and the pi_manager makes manipulations on result files (intermediate access). We could skip the creation of `in` folder however `out` folder must be created. I have tested the latest for pi_csic and it works.

**Comment by aremazeilles** [comment]
This is not clear to me: we have several options:

1. create the in out folder in the image through the docker file, during the image connection, as we do it [right now](https://github.com/eurobench/pi_python_duration/blob/master/Dockerfile#L35).
2. create them directly when launching the docker image.

If we go for the second, I understand that we have to, before calling the pi docker, create locally the out folder, otherwise the folder created gets root right. Is it what you are referring to?

**Comment by alfonsotecnalia** [comment]
It seems it was a permissions issue of the created folder for the results in the pi_manager. I have done some tests with pi_duration_sample (and it works). I will do some with pi_cscic and confirm it.

**Comment by alfonsotecnalia** [comment]
Tests done. I have created a branch in_out for example PIs in github which removes the lines for creating in/out directories in the dockerfile. I will create the merge requests for them.
